from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(805, 533)
        self.exitButton = QtWidgets.QPushButton(Dialog)
        self.exitButton.setGeometry(QtCore.QRect(320, 480, 113, 32))
        self.exitButton.setObjectName("exitButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 60, 16))
        self.label.setObjectName("label")
        self.fileHandlingFrame = QtWidgets.QFrame(Dialog)
        self.fileHandlingFrame.setGeometry(QtCore.QRect(20, 30, 631, 81))
        self.fileHandlingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fileHandlingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fileHandlingFrame.setObjectName("fileHandlingFrame")
        self.openReadButton = QtWidgets.QPushButton(self.fileHandlingFrame)
        self.openReadButton.setGeometry(QtCore.QRect(10, 20, 201, 41))
        self.openReadButton.setObjectName("openReadButton")
        self.filePath = QtWidgets.QTextEdit(self.fileHandlingFrame)
        self.filePath.setGeometry(QtCore.QRect(220, 10, 401, 61))
        self.filePath.setObjectName("filePath")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 81, 16))
        self.label_2.setObjectName("label_2")
        self.ductReportFrame = QtWidgets.QFrame(Dialog)
        self.ductReportFrame.setGeometry(QtCore.QRect(20, 150, 741, 311))
        self.ductReportFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ductReportFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ductReportFrame.setObjectName("ductReportFrame")
        self.runLengthFrame = QtWidgets.QFrame(self.ductReportFrame)
        self.runLengthFrame.setGeometry(QtCore.QRect(520, 29, 211, 141))
        self.runLengthFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.runLengthFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.runLengthFrame.setObjectName("runLengthFrame")
        self.label_4 = QtWidgets.QLabel(self.runLengthFrame)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.label_4.setObjectName("label_4")
        self.diffuserID = QtWidgets.QLineEdit(self.runLengthFrame)
        self.diffuserID.setGeometry(QtCore.QRect(90, 10, 113, 21))
        self.diffuserID.setObjectName("diffuserID")
        self.label_5 = QtWidgets.QLabel(self.runLengthFrame)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.label_5.setObjectName("label_5")
        self.runLength = QtWidgets.QLineEdit(self.runLengthFrame)
        self.runLength.setGeometry(QtCore.QRect(90, 40, 113, 21))
        self.runLength.setObjectName("runLength")
        self.label_6 = QtWidgets.QLabel(self.runLengthFrame)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_6.setObjectName("label_6")
        self.longestRunPath = QtWidgets.QTextEdit(self.runLengthFrame)
        self.longestRunPath.setGeometry(QtCore.QRect(10, 90, 191, 41))
        self.longestRunPath.setObjectName("longestRunPath")
        self.label_3 = QtWidgets.QLabel(self.ductReportFrame)
        self.label_3.setGeometry(QtCore.QRect(521, 10, 131, 16))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.ductReportFrame)
        self.label_7.setGeometry(QtCore.QRect(521, 180, 181, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.ductReportFrame)
        self.label_8.setGeometry(QtCore.QRect(531, 200, 91, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.ductReportFrame)
        self.label_9.setGeometry(QtCore.QRect(531, 240, 91, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.ductReportFrame)
        self.label_10.setGeometry(QtCore.QRect(531, 220, 181, 16))
        self.label_10.setObjectName("label_10")
        self.ductReport = QtWidgets.QTextEdit(self.ductReportFrame)
        self.ductReport.setGeometry(QtCore.QRect(10, 20, 491, 251))
        self.ductReport.setObjectName("ductReport")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.exitButton.setText(_translate("Dialog", "Exit"))
        self.label.setText(_translate("Dialog", "Duct File"))
        self.openReadButton.setText(_translate("Dialog", "Open and Read a Duct File"))
        self.filePath.setText(_translate("Dialog", "Duct Design Input File 1.txt"))
        self.label_2.setText(_translate("Dialog", "Duct Report"))
        self.label_4.setText(_translate("Dialog", "Diffuser ID"))
        self.label_5.setText(_translate("Dialog", "Run Length"))
        self.label_6.setText(_translate("Dialog", "Longest Run Path"))
        self.label_3.setText(_translate("Dialog", "Longest Length Run"))
        self.label_7.setText(_translate("Dialog", "Contributors to this program:"))
        self.label_8.setText(_translate("Dialog", "Jason Conway"))
        self.label_9.setText(_translate("Dialog", "Malorie Travis"))
        self.label_10.setText(_translate("Dialog", "Abdalrahman (Mann) Mansy"))

