# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTSatWater.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(463, 640)
        self.Input = QtWidgets.QGroupBox(Dialog)
        self.Input.setGeometry(QtCore.QRect(20, 10, 411, 241))
        self.Input.setObjectName("Input")
        self.lineEdit_pressure = QtWidgets.QLineEdit(self.Input)
        self.lineEdit_pressure.setGeometry(QtCore.QRect(150, 50, 113, 25))
        self.lineEdit_pressure.setObjectName("lineEdit_pressure")
        self.lineEdit_quality = QtWidgets.QLineEdit(self.Input)
        self.lineEdit_quality.setGeometry(QtCore.QRect(150, 100, 113, 25))
        self.lineEdit_quality.setObjectName("lineEdit_quality")
        self.label = QtWidgets.QLabel(self.Input)
        self.label.setGeometry(QtCore.QRect(60, 50, 68, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Input)
        self.label_2.setGeometry(QtCore.QRect(60, 110, 68, 19))
        self.label_2.setObjectName("label_2")
        self.pushButton_calculate = QtWidgets.QPushButton(self.Input)
        self.pushButton_calculate.setGeometry(QtCore.QRect(140, 160, 112, 34))
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.label_3 = QtWidgets.QLabel(self.Input)
        self.label_3.setGeometry(QtCore.QRect(290, 50, 58, 16))
        self.label_3.setObjectName("label_3")
        self.Output = QtWidgets.QGroupBox(Dialog)
        self.Output.setGeometry(QtCore.QRect(20, 280, 423, 299))
        self.Output.setObjectName("Output")
        self.label_4 = QtWidgets.QLabel(self.Output)
        self.label_4.setGeometry(QtCore.QRect(30, 50, 81, 19))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Output)
        self.label_5.setGeometry(QtCore.QRect(30, 110, 68, 19))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Output)
        self.label_6.setGeometry(QtCore.QRect(30, 170, 68, 19))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.Output)
        self.label_7.setGeometry(QtCore.QRect(30, 230, 91, 19))
        self.label_7.setObjectName("label_7")
        self.lineEdit_temp = QtWidgets.QLineEdit(self.Output)
        self.lineEdit_temp.setGeometry(QtCore.QRect(150, 50, 113, 25))
        self.lineEdit_temp.setObjectName("lineEdit_temp")
        self.lineEdit_enthalpy = QtWidgets.QLineEdit(self.Output)
        self.lineEdit_enthalpy.setGeometry(QtCore.QRect(150, 110, 113, 25))
        self.lineEdit_enthalpy.setObjectName("lineEdit_enthalpy")
        self.lineEdit_entropy = QtWidgets.QLineEdit(self.Output)
        self.lineEdit_entropy.setGeometry(QtCore.QRect(150, 170, 113, 25))
        self.lineEdit_entropy.setObjectName("lineEdit_entropy")
        self.lineEdit_specificVolume = QtWidgets.QLineEdit(self.Output)
        self.lineEdit_specificVolume.setGeometry(QtCore.QRect(150, 230, 113, 25))
        self.lineEdit_specificVolume.setObjectName("lineEdit_specificVolume")
        self.label_16 = QtWidgets.QLabel(self.Output)
        self.label_16.setGeometry(QtCore.QRect(300, 50, 21, 20))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.Output)
        self.label_17.setGeometry(QtCore.QRect(300, 110, 41, 20))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.Output)
        self.label_18.setGeometry(QtCore.QRect(300, 170, 51, 20))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.Output)
        self.label_19.setGeometry(QtCore.QRect(300, 230, 51, 20))
        self.label_19.setObjectName("label_19")
        self.pushButton_Exit = QtWidgets.QPushButton(Dialog)
        self.pushButton_Exit.setGeometry(QtCore.QRect(180, 590, 111, 32))
        self.pushButton_Exit.setObjectName("pushButton_Exit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Input.setTitle(_translate("Dialog", "Input"))
        self.label.setText(_translate("Dialog", "Pressure"))
        self.label_2.setText(_translate("Dialog", "Quality"))
        self.pushButton_calculate.setText(_translate("Dialog", "Calculate"))
        self.label_3.setText(_translate("Dialog", "bars"))
        self.Output.setTitle(_translate("Dialog", "Output"))
        self.label_4.setText(_translate("Dialog", "Temperature"))
        self.label_5.setText(_translate("Dialog", "Enthalpy"))
        self.label_6.setText(_translate("Dialog", "Entropy"))
        self.label_7.setText(_translate("Dialog", "Spec. Volume"))
        self.label_16.setText(_translate("Dialog", "C"))
        self.label_17.setText(_translate("Dialog", "kJ/kg"))
        self.label_18.setText(_translate("Dialog", "kJ/kg-K"))
        self.label_19.setText(_translate("Dialog", "m^3/kg"))
        self.pushButton_Exit.setText(_translate("Dialog", "Exit"))
